/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 29-May-2023 16:19:37
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 9
 * Denominator Length  : 9
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2020b\extern\include\tmwtypes.h 
 */
const int NL = 9;
const real64_T NUM[9] = {
  0.0002744802260304,-0.001268109100545,   0.0027258042934,-0.003881916543634,
   0.004299482249499,-0.003881916543634,   0.0027258042934,-0.001268109100545,
  0.0002744802260304
};
const int DL = 9;
const real64_T DEN[9] = {
                   1,   -7.562747349582,    25.03894818939,   -47.40262515418,
      56.12602930094,   -42.56064904029,    20.18549467043,   -5.474491339547,
     0.6500407228488
};
