/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 29-May-2023 16:13:29
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 15
 * Denominator Length  : 15
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2020b\extern\include\tmwtypes.h 
 */
const int NL = 15;
const real64_T NUM[15] = {
  0.0004247093750489,-0.003041223305884,  0.01023949574334, -0.02170434024726,
    0.03211840412627, -0.03355798707444,  0.02165503883797,                 0,
   -0.02165503883797,  0.03355798707444, -0.03211840412627,  0.02170434024726,
   -0.01023949574334, 0.003041223305884,-0.0004247093750489
};
const int DL = 15;
const real64_T DEN[15] = {
                   1,   -10.63907786689,    53.73091237974,   -170.5925502096,
      380.1647186452,   -628.7664320344,    795.6861372426,     -782.50775649,
      600.9236925876,   -358.6313721795,    163.7672426328,   -55.50765914845,
      13.20833761334,   -1.976716613661,   0.1405384578739
};
